// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Apr 30 13:19:07 2018

cic_filter cic_filter_inst
(
	.clk_50M(clk_50M_sig) ,	// input  clk_50M_sig
	.clk(clk_sig) ,	// input  clk_sig
	.sensor_in(sensor_in_sig) ,	// input [5:0] sensor_in_sig
	.rst(rst_sig) ,	// input  rst_sig
	.data_out1(data_out1_sig) ,	// output [15:0] data_out1_sig
	.data_out2(data_out2_sig) ,	// output [15:0] data_out2_sig
	.data_out3(data_out3_sig) ,	// output [15:0] data_out3_sig
	.data_out4(data_out4_sig) ,	// output [15:0] data_out4_sig
	.data_out5(data_out5_sig) ,	// output [15:0] data_out5_sig
	.data_out6(data_out6_sig) ,	// output [15:0] data_out6_sig
	.out_en(out_en_sig) 	// output  out_en_sig
);

